# Generated by Django 4.2.10 on 2024-03-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Confirmed', max_length=20),
        ),
    ]
